language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8-dev"

before_install:
# We need GraphViz to draw figures of graphs and lattices:
 - "sudo apt-get install graphviz"
# We need numpy and sympy
 - pip install numpy sympy
# We need these to call GraphViz from Python:
 - "pip install --upgrade pip"
 - "pip install pydot-ng pyparsing"

script:
 - "python graphs.py"
