language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"

before_install:
 # We need GraphViz to draw figures of graphs and lattices:
 - "sudo apt-get install graphviz"
 - "pip install --upgrade pip"
 # We need these to call GraphViz from Python:
 - "pip install pydot-ng pyparsing"
 - "pip install flake8 flake8-black black flake8-comprehensions flake8-blind-except flake8-bugbear flake8-docstrings flake8-rst-docstrings"
 - flake8 .

script:
 - "python graphs.py"
